services:
  chatapi:
    image: chatapi
    build:
      context: .
      dockerfile: ChatApi/Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mydb"
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"
  adminer:
      image: adminer
      restart: always
      ports:
        - "8085:8080"
      depends_on:
        - db
volumes:
  pgdata:
